services:
  text_db:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TORCH_VARIANT=${TORCH_VARIANT:-cpu} # rocm
    working_dir: /app
    tty: true
    stdin_open: true
    ports:
      - "8901:8901"
    environment:
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
      - DB_NAME=${PG_NAME}
      - DB_USER=${PG_USER}
      - DB_PASSWORD=${PG_PASSWORD}
    depends_on:
      - postgres
  postgres:
    image: pgvector/pgvector:pg18
    restart: on-failure
    # ports:
    #   - "5432:5432"
    volumes:
      - ./law_chunks_backup.sql:/docker-entrypoint-initdb.d/law_chunks_backup.sql
      - pgdata:/var/lib/postgresql/
    environment:
      POSTGRES_DB: ${PG_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
volumes:
  pgdata:
