services:
  text_db:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    tty: true
    stdin_open: true
    ports:
      - "8901:8000"
    environment:
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
      - DB_NAME=${PG_NAME}
      - DB_USER=${PG_USER}
      - DB_PASSWORD=${PG_PASSWORD}
    depends_on:
      - postgres
  postgres:
    # 使用已經預裝了 pgvector 擴展的映象
    image: pgvector/pgvector:pg18
    restart: on-failure
    # ports:
    #   - "5432:5432"
    volumes:
      - ./law_chunks_backup.sql:/docker-entrypoint-initdb.d/law_chunks_backup.sql
      # - ./pgdata:/var/lib/postgresql/
    environment:
      # 設定資料庫名稱、使用者和密碼 (與您 Python 連線字串保持一致)
      POSTGRES_DB: ${PG_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
