services:
  text_db:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    # interactive: true
    tty: true
    stdin_open: true
    ports:
      - "8901:8000"
    env_file:
      - .env
  postgres:
    # 使用已經預裝了 pgvector 擴展的映象
    image: pgvector/pgvector:pg18
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./pgdata:/var/lib/postgresql/
    environment:
      # 設定資料庫名稱、使用者和密碼 (與您 Python 連線字串保持一致)
      POSTGRES_DB: ${PG_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
